# Generated by Django 5.1.7 on 2025-03-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50)),
                ('carrier_name', models.CharField(max_length=100)),
                ('home_terminal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=200)),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('current_cycle_used', models.FloatField(help_text='Hours already used in the current cycle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route_data', models.JSONField(blank=True, null=True)),
                ('estimated_miles', models.FloatField(blank=True, null=True)),
                ('estimated_duration', models.FloatField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='tripapi.driver')),
            ],
        ),
        migrations.CreateModel(
            name='RestStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('rest_duration', models.FloatField(help_text='Duration of rest in hours')),
                ('is_fuel_stop', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_stops', to='tripapi.tripplan')),
            ],
        ),
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('log_data', models.JSONField(help_text='JSON representation of the ELD log entries')),
                ('total_driving_hours', models.FloatField()),
                ('total_on_duty_hours', models.FloatField()),
                ('total_miles_driven', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to='tripapi.tripplan')),
            ],
        ),
    ]
