# Generated by Django 5.1.7 on 2025-03-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapi', '0002_tripplan_current_location_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldlog',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='eldlog',
            name='total_off_duty_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='eldlog',
            name='total_sleeper_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='eldlog',
            name='total_driving_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='eldlog',
            name='total_miles_driven',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='eldlog',
            name='total_on_duty_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
